#!/bin/sh

# Fill in certain identifiers for the jail build and update scripts.
#
# Tinderbox passes in the PB, JAIL, JAIL_ARCH and UPDATE_CMD variables.

USCRIPT=${PB}/jails/${JAIL}/update.sh
BSCRIPT=${PB}/jails/${JAIL}/build.sh

case ${JAIL} in
8-svos_9-i386)
    OSNAME=i386-SVOS9
    OSTYPE=SVOS
    ;;
8-svos_9-amd64)
    OSNAME=amd64-SVOS9
    OSTYPE=SVOS
    ;;
8-freebsd_8-amd64)
    OSNAME=amd64-FreeBSD8
    OSTYPE=FREEBSD
    ;;
6-svos_6-i386)
    OSNAME=freebsd6
    OSTYPE=SVOS
    ;;
6-svos_6-amd64)
    OSNAME=amd64-FreeBSD6
    OSTYPE=SVOS
    ;;
6-freebsd_6-i386)
    OSNAME=freebsd6
    OSTYPE=FREEBSD
    ;;
6-freebsd_6-amd64)
    OSNAME=amd64-FreeBSD6
    OSTYPE=FREEBSD
    ;;
*)
    echo "Tinderbox: unknown jail ${JAIL}" 1>&2 && exit 1
    ;;
esac

# JAILDIR is a path, so it must be escaped before being used in a sed command.
JAILDIR=$(echo ${PB}/jails/${JAIL} | sed 's?\/?\\\/?g')

for script in ${USCRIPT} ${BSCRIPT}; do
    [ -f $script ] || continue
    sed -i '' -e 's/^ARCH=%%$/ARCH='${JAIL_ARCH}'/' \
        -e 's/^JAILDIR=%%$/JAILDIR='${JAILDIR}'/' \
        -e 's/^OSNAME=%%$/OSNAME='${OSNAME}'/' \
        -e 's/^OSTYPE=%%$/OSTYPE='${OSTYPE}'/' ${script}
done
